const {test}=require('node:test'),assert=require('node:assert/strict');
const {BattleServer}=require('../app/battle.cjs');
function arena(count=50){let now=100;const messages=[],results=[];const s=new BattleServer((id,m)=>messages.push({id,m}),()=>now,r=>results.push(r));for(let i=0;i<count;i++){const id=String(i);s.connect(id,{userId:'u'+i,name:'토끼'+i});s.receive(id,i?{type:'join',code:s.peers.get('0').room}:{type:'create'});}const room=s.rooms.get(s.peers.get('0').room);return {s,room,messages,results,time(v){now=v;},start(){for(const id of room.players)s.receive(id,{type:'ready',ready:true});s.receive('0',{type:'start'});now=3100;s.tick();}};}
const clear={rows:[18,19,20,21],combo:0,perfect:false,chained:false,spin:''};
test('host needs no ready state; one ready visitor enables all-player start',()=>{const x=arena(3),{s,room}=x;s.receive('0',{type:'ready',ready:true});assert.equal(s.peers.get('0').ready,false);s.receive('0',{type:'start'});assert.equal(room.phase,'waiting');s.receive('1',{type:'ready',ready:true});s.receive('0',{type:'start'});assert.equal(room.phase,'countdown');assert.equal(room.members.size,3);assert.equal(s.peers.get('2').ready,false);});
test('blank title defaults to trusted nickname; custom title is trimmed',()=>{const x=arena(2);assert.equal(x.room.title,'토끼0s_room');x.s.connect('new',{name:'guest_123456',userId:'new'});x.s.receive('new',{type:'create',title:'   ',name:'spoofed'});assert.equal(x.s.rooms.get(x.s.peers.get('new').room).title,'guest_123456s_room');x.s.receive('new',{type:'leave'});x.s.receive('new',{type:'create',title:'  테스트 방  '});assert.equal(x.s.rooms.get(x.s.peers.get('new').room).title,'테스트 방');});
test('50 participants, 51st rejected, host and all-ready gate enforced',()=>{const x=arena(),{s,room}=x;assert.equal(room.players.length,50);s.connect('extra');s.receive('extra',{type:'join',code:room.code});assert.equal(s.peers.get('extra').room,null);s.receive('1',{type:'start'});assert.equal(room.phase,'waiting');s.receive('0',{type:'start'});assert.equal(room.phase,'waiting');x.start();assert.equal(room.phase,'playing');});
test('every state includes all 50 compact boards but only own full board',()=>{const x=arena();x.start();x.messages.length=0;x.s.snapshot(x.room,3100);assert.equal(x.messages.length,50);for(const {id,m} of x.messages){assert.equal(m.players.length,1);assert.equal(m.players[0].id,id);assert.equal(m.roster.length,50);assert.ok(m.roster.every(p=>p.mini.length===200&&/^[.IJLOSTZG]+$/.test(p.mini)));assert.ok(Buffer.byteLength(JSON.stringify(m))<22000);}});
test('each attack draws a random live opponent; never self, never eliminated, not multicast',()=>{const x=arena(5);x.start();const {s,room}=x;s.eliminate(room,[s.peers.get('4')],'forfeit',3200);const picked=new Set();for(let i=0;i<120;i++){for(const p of room.members.values())p.pending=[];s.lock(room,s.peers.get('0'),clear,3300+i);const recipients=[...room.members.values()].filter(p=>p.pending.length);assert.equal(recipients.length,1);assert.notEqual(recipients[0].id,'0');assert.notEqual(recipients[0].id,'4');assert.equal(recipients[0].pending.length,4);picked.add(recipients[0].id);}assert.equal(picked.size,3);});
test('departed player entering a different room cannot mutate old standings',()=>{const x=arena(3);x.start();const {s,room}=x;s.peers.get('1').game.score=123;s.receive('1',{type:'leave'});s.receive('1',{type:'create'});assert.equal(room.phase,'playing');s.receive('2',{type:'forfeit'});assert.equal(room.result.winner,'0');assert.equal(x.results.length,1);assert.equal(x.results[0].players.find(p=>p.id==='1').score,123);assert.equal(x.results[0].players.find(p=>p.id==='1').placement,3);});
test('simultaneous final topouts produce no winner and no win credit',()=>{const x=arena(3);x.start();for(const p of x.room.members.values())p.game.over=true;x.s.checkOver(x.room,3500);assert.equal(x.room.result.winner,null);assert.ok(x.results[0].players.every(p=>!p.won&&p.placement===1));});
test('duplicate account cannot connect twice and manual target requests do nothing',()=>{const x=arena(3);x.start();x.s.connect('dup',{userId:'u0'});assert.equal(x.s.peers.has('dup'),false);const p=x.s.peers.get('0'),before=p.target;x.s.receive('0',{type:'target',id:'2'});assert.equal(p.target,before);});
