const {test}=require('node:test');
const assert=require('node:assert/strict');
const {BattleServer}=require('../app/battle.cjs');
const {Game,clone,attackLines,seededRandom}=require('../frontend/js/engine.js');
function setup(){let now=100;const sent=[];const s=new BattleServer((id,m)=>sent.push({id,m:structuredClone(m)}),()=>now);s.connect('a');s.connect('b');s.receive('a',{type:'create',name:'Alice'});const code=s.peers.get('a').room;s.receive('b',{type:'join',code,name:'Bob'});return {s,sent,room:s.rooms.get(code),time:v=>now=v,start(){s.receive('a',{type:'ready',ready:true});s.receive('b',{type:'ready',ready:true});s.receive('a',{type:'start'});now=3100;s.tick();}};}
function clear(n,extra={}){return {rows:Array.from({length:n},(_,i)=>21-i),combo:0,chained:false,perfect:false,spin:'',...extra};}
function well(g,n=4){g.board=Array.from({length:22},()=>Array(10).fill(null));for(let y=22-n;y<22;y++)g.board[y]=Array.from({length:10},(_,x)=>x===5?null:'#647580');g.current=clone('I');g.rotate(1,0);g.current.x=3;g.current.y=10;g.resetPiece(3100);}
test('attack table, mini, combo, B2B and perfect clear are explicit',()=>{
  assert.deepEqual([1,2,3,4].map(n=>attackLines(clear(n))),[0,1,2,4]);
  assert.deepEqual([1,2,3].map(n=>attackLines(clear(n,{spin:'T-SPIN'}))),[2,4,6]);
  assert.equal(attackLines(clear(1,{spin:'T-SPIN MINI'})),0);assert.equal(attackLines(clear(2,{spin:'T-SPIN MINI'})),1);
  assert.deepEqual([0,1,2,3,4,5,6,7,20].map(combo=>attackLines(clear(1,{combo}))),[0,1,1,2,2,3,3,4,4]);
  assert.equal(attackLines(clear(4,{chained:true,perfect:true,combo:7})),19);assert.equal(attackLines(clear(0,{spin:'T-SPIN',combo:9,chained:true})),0);
});
test('seeded sequences match across hundreds of bags',()=>{const a=new Game(seededRandom(77)),b=new Game(seededRandom(77));for(let i=0;i<500;i++){assert.equal(a.current.type,b.current.type);assert.deepEqual(a.queue,b.queue);a.spawn(i);b.spawn(i);}});
test('server rotate-180 uses the same L/J tuck rules and broadcasts the final position',()=>{for(const f of require('./spin-fixtures.cjs')){const x=setup();x.start();const {s,room,sent}=x,g=s.peers.get('a').game;g.current=clone(f.type);g.rotate(f.rotation,3100);g.current.x=f.x;f.rows.forEach((r,i)=>g.board[16+i]=[...r].map(v=>v==='#'?'#abc':null));while(g.down(3100)){}s.receive('a',{type:'input',match:room.match,seq:1,action:'rotate-180',edge:'tap'});assert.equal(g.current.x,f.afterX);assert.equal(g.current.y,f.y);assert.equal(g.current.r,f.afterR);s.snapshot(room,3100);const opponentView=sent.filter(e=>e.id==='b'&&e.m.type==='state').at(-1).m.roster.find(p=>p.id==='a');assert.equal(opponentView.mini.length,200);for(const c of require('../frontend/js/engine.js').cells(g.current))if(c.y>=2)assert.equal(opponentView.mini[(c.y-2)*10+c.x],f.type);}});
test('more than two players can join; rooms remain isolated',()=>{const {s,room,sent}=setup();s.connect('c');s.receive('c',{type:'join',code:'XXXXXX'});assert.match(sent.at(-1).m.message,/존재하지/);s.receive('c',{type:'join',code:room.code});assert.equal(s.peers.get('c').room,room.code);assert.equal(room.players.length,3);s.receive('a',{type:'create'});assert.equal(s.rooms.size,1);});
test('both ready are required; countdown rejects input and starts identical pieces',()=>{const x=setup(),{s,room}=x;s.receive('a',{type:'ready',ready:true});assert.equal(room.phase,'waiting');s.receive('b',{type:'ready',ready:true});s.receive('a',{type:'start'});assert.equal(room.phase,'countdown');s.receive('a',{type:'input',match:room.match,seq:1,action:'drop',edge:'tap'});assert.equal(s.peers.get('a').game.pieces,0);x.time(3099);s.tick();assert.equal(room.phase,'countdown');x.time(3100);s.tick();assert.equal(room.phase,'playing');assert.deepEqual(s.peers.get('a').game.queue,s.peers.get('b').game.queue);});
test('server ignores fabricated attacks, stale matches and replayed inputs',()=>{const x=setup();x.start();const {s,room}=x,a=s.peers.get('a'),b=s.peers.get('b');s.receive('a',{type:'attack',lines:999});assert.equal(b.pending.length,0);const m={type:'input',match:room.match,seq:1,action:'drop',edge:'tap'};s.receive('a',{...m,match:'old'});assert.equal(a.game.pieces,0);s.receive('a',m);assert.equal(a.game.pieces,1);x.time(4000);s.receive('a',m);assert.equal(a.game.pieces,1);});
test('real server hard drop calculates and sends a Tetris perfect-clear attack',()=>{const x=setup();x.start();const {s,room}=x,a=s.peers.get('a'),b=s.peers.get('b');well(a.game);s.receive('a',{type:'input',match:room.match,seq:1,action:'drop',edge:'tap'});assert.equal(a.game.lines,4);assert.equal(a.sent,14);assert.equal(b.pending.length,14);assert.equal(new Set(b.pending.map(p=>p.hole)).size,1);assert.ok(b.pending.every(p=>p.due===4300));});
test('FIFO cancellation consumes warning garbage before sending remainder',()=>{const x=setup();x.start();const {s,room}=x,a=s.peers.get('a'),b=s.peers.get('b');a.pending=[{hole:3,due:9999},{hole:4,due:9999}];s.lock(room,a,clear(4),3200);assert.equal(a.pending.length,0);assert.equal(a.cancelled,2);assert.equal(a.sent,2);assert.equal(b.pending.length,2);});
test('attack delay, clear-stalling and max eight garbage per nonclear placement',()=>{const x=setup();x.start();const {s,room}=x,a=s.peers.get('a');a.pending=Array.from({length:12},()=>({hole:4,due:5000}));s.lock(room,a,clear(0),4999);assert.equal(a.pending.length,12);s.lock(room,a,clear(1),5000);assert.equal(a.pending.length,12);s.lock(room,a,clear(0),5001);assert.equal(a.pending.length,4);assert.equal(a.received,8);assert.ok(a.game.board.slice(-8).every(r=>r.filter(Boolean).length===9&&r[4]===null));s.lock(room,a,clear(0),6000);assert.equal(a.pending.length,0);});
test('counterattacks cancel queued attacks without a garbage injection',()=>{const x=setup();x.start();const {s,room}=x,a=s.peers.get('a'),b=s.peers.get('b');s.lock(room,a,clear(4),3200);s.lock(room,b,clear(4),3200);assert.equal(a.pending.length,0);assert.equal(b.pending.length,0);assert.equal(b.cancelled,4);});
test('garbage overflow and blocked spawn top out without changing dimensions',()=>{const g=new Game();g.board[0][0]='#abc';g.addGarbage([4],10);assert.equal(g.over,true);assert.equal(g.board.length,22);assert.ok(g.board.every(r=>r.length===10));const other=new Game();other.addGarbage(Array(22).fill(0),0);assert.equal(other.over,true);});
test('simultaneous topout is draw and result finalizes exactly once',()=>{const x=setup();x.start();const {s,room,sent}=x;s.peers.get('a').game.over=true;s.peers.get('b').game.over=true;s.checkOver(room,3300);assert.equal(room.result.winner,null);const result=room.result;s.finish(room,'a','forfeit',3400);assert.equal(room.result,result);assert.equal(sent.filter(e=>e.id==='a'&&e.m.type==='room'&&e.m.phase==='finished').length,1);});
test('disconnect/leave forfeit, readiness reset, host handover and empty room deletion',()=>{const x=setup();x.start();const {s,room}=x;s.disconnect('a');assert.equal(room.phase,'finished');assert.equal(room.result.winner,'b');assert.equal(room.result.reason,'disconnect');assert.equal(s.peers.get('b').ready,false);s.connect('c');s.receive('c',{type:'join',code:room.code});assert.equal(room.players.length,2);s.disconnect('b');s.disconnect('c');assert.equal(s.rooms.size,0);});
test('rematch replaces boards, pending attacks and match IDs only when both ready',()=>{const x=setup();x.start();const {s,room}=x;const match=room.match;s.peers.get('a').pending.push({hole:1,due:0});s.receive('a',{type:'forfeit'});s.receive('a',{type:'ready',ready:true});assert.equal(room.phase,'finished');s.receive('b',{type:'ready',ready:true});s.receive('a',{type:'start'});assert.equal(room.phase,'countdown');assert.notEqual(room.match,match);assert.equal(s.peers.get('a').pending.length,0);assert.equal(s.peers.get('a').game.pieces,0);});
test('held input honors DAS / instant ARR / release and never sticks after focus release',()=>{const x=setup();x.start();const {s,room}=x,a=s.peers.get('a');a.game.current=clone('O');s.receive('a',{type:'settings',das:150,arr:0});const input=(seq,action,edge)=>s.receive('a',{type:'input',match:room.match,seq,action,edge});input(1,'left','down');assert.equal(a.game.current.x,3);x.time(3249);s.tick();assert.equal(a.game.current.x,3);x.time(3250);s.tick();assert.equal(a.game.current.x,0);input(2,'right','down');x.time(3400);s.tick();assert.equal(a.game.current.x,8);input(3,'right','up');x.time(3550);s.tick();assert.equal(a.game.current.x,0);input(4,'release','tap');assert.equal(a.direction,null);});
test('heartbeat expiry forfeits disconnected player without evicting live opponent',()=>{const x=setup();x.start();const {s,room}=x;x.time(20200);s.receive('b',{type:'ping',at:1});s.tick();assert.equal(room.result.winner,'b');assert.equal(s.peers.has('a'),false);});
test('chat stays in room, bounds names/content, and rate-limits repeated messages',()=>{const x=setup(),{s,sent}=x;s.connect('c');sent.length=0;s.receive('a',{type:'chat',text:'<img src=x onerror=alert(1)>'});assert.deepEqual(sent.map(e=>e.id),['a','b']);assert.equal(sent[0].m.text,'<img src=x onerror=alert(1)>');s.receive('a',{type:'chat',text:'spam'});assert.equal(sent.at(-1).m.type,'error');x.time(1000);s.receive('a',{type:'chat',text:'x'.repeat(500)});assert.equal(sent.at(-1).m.text.length,200);});
test('new participants never inherit the previous match result or board',()=>{const x=setup();x.start();const {s,room,sent}=x;s.disconnect('b');assert.equal(room.phase,'finished');s.connect('c');s.receive('c',{type:'join',code:room.code});assert.equal(room.phase,'waiting');assert.equal(room.result,null);assert.equal(room.match,null);assert.equal(s.peers.get('a').game,null);assert.equal(s.peers.get('c').game,null);assert.equal(sent.at(-1).m.type,'state');assert.equal(sent.at(-1).m.elapsed,0);s.receive('c',{type:'leave'});s.receive('c',{type:'create'});assert.equal(s.peers.get('c').game,null);});
