const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Game,PIECES,bag,clone,cells,scoreClear}=require('../frontend/js/engine.js');
const empty=()=>Array.from({length:22},()=>Array(10).fill(null));
function rng(seed=19){return ()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);}
function well(g,n=4){g.board=empty();for(let y=22-n;y<22;y++)g.board[y]=Array.from({length:10},(_,x)=>x===5?null:'#abc');g.current=clone('I');g.rotate(1,0);g.current.x=3;g.current.y=10;g.resetPiece(0);}
test('every bag contains all seven pieces once',()=>{const random=rng();for(let i=0;i<1000;i++)assert.deepEqual(bag(random).sort(),Object.keys(PIECES).sort());});
test('Fisher-Yates permits all 5040 permutations through its choices',()=>{
  const permutations=new Set();
  function visit(choices,i){if(i===0){let p=0;permutations.add(bag(()=>choices[p++]).join(''));return;}for(let j=0;j<=i;j++)visit([...choices,(j+.5)/(i+1)],i-1);}
  visit([],6);assert.equal(permutations.size,5040);
});
test('all pieces spawn centered with independent matrices',()=>{for(const type of Object.keys(PIECES)){const p=clone(type);assert.equal(p.x,Math.floor((10-p.m[0].length)/2));assert.equal(cells(p).length,4);p.m[0][0]=9;assert.notEqual(PIECES[type].m[0][0],9);}});
test('four rotations restore each piece and never alter templates',()=>{for(const type of Object.keys(PIECES).filter(t=>t!=='O')){const g=new Game();g.current=clone(type);g.current.y=8;const original=JSON.stringify(g.current.m);for(let i=0;i<4;i++)assert.equal(g.rotate(1,i),true);assert.equal(JSON.stringify(g.current.m),original);assert.equal(g.current.r,0);}});
test('wall kick recovers a T rotation near the left wall',()=>{const g=new Game();g.current=clone('T');g.rotate(1,0);g.current.x=-1;g.current.y=10;assert.equal(g.blocked(),false);assert.equal(g.rotate(-1,10),true);assert.equal(g.current.x,0);assert.equal(g.blocked(),false);});
test('I floor kick rotates a horizontal piece at the floor',()=>{const g=new Game();g.current=clone('I');g.current.y=20;assert.equal(g.rotate(1,10),true);assert.equal(g.blocked(),false);assert.ok(g.current.y<20);});
test('failed rotation leaves piece and lock state unchanged',()=>{const g=new Game();g.current=clone('T');g.current.y=10;g.board=Array.from({length:22},()=>Array(10).fill('#abc'));for(const {x,y} of cells(g.current))g.board[y][x]=null;const before=JSON.stringify(g.current);assert.equal(g.rotate(1,20),false);assert.equal(JSON.stringify(g.current),before);assert.equal(g.lockResets,0);});
test('failed 180 rotation preserves the entire piece and lock state',()=>{const g=new Game();g.current=clone('L');g.current.y=8;g.board=Array.from({length:22},()=>Array(10).fill('#abc'));for(const {x,y} of cells(g.current))g.board[y][x]=null;g.lastTurn=-1;g.lastRotate=true;g.lastKick=3;g.groundedAt=5;g.lockResets=7;const before=JSON.stringify(g);assert.equal(g.rotate(2,10),false);assert.equal(JSON.stringify(g),before);});
test('L and J 180 tucks enter mirrored cavities directly and reset lock only once',()=>{
  for(const f of require('./spin-fixtures.cjs')){const g=new Game();g.current=clone(f.type);g.rotate(f.rotation,0);g.current.x=f.x;f.rows.forEach((r,i)=>g.board[16+i]=[...r].map(v=>v==='#'?'#abc':null));while(g.down(10)){}assert.equal(g.current.y,f.y);g.groundedAt=10;g.lockResets=0;
    assert.equal(g.rotate(2,20),true);assert.equal(g.current.r,f.afterR);assert.equal(g.current.x,f.afterX);assert.equal(g.current.y,f.y);assert.equal(g.lastKick,1);assert.equal(g.lastTurn,2);assert.equal(g.lockResets,1);assert.equal(g.blocked(),false);assert.equal(g.grounded(),true);assert.equal(g.hardDrop(20).spin,'');
  }
});
test('two half turns restore all non-O pieces in open space',()=>{for(const type of Object.keys(PIECES).filter(t=>t!=='O'))for(let r=0;r<4;r++){const g=new Game();g.current=clone(type);g.current.y=8;for(let i=0;i<r;i++)g.rotate(1,0);const before=JSON.stringify(g.current);assert.equal(g.rotate(2,10),true);assert.equal(g.rotate(2,20),true);assert.equal(JSON.stringify(g.current),before);}});
test('180 floor and wall kicks stay inside the board for I/J/L/S/T/Z',()=>{for(const type of ['I','J','L','S','T','Z']){const g=new Game();g.current=clone(type);while(g.down(0)){}assert.equal(g.rotate(2,10),true);assert.equal(g.blocked(),false);for(const dir of [-1,1]){while(g.move(dir,20)){}if(g.rotate(2,30))assert.equal(g.blocked(),false);}}});
test('180 kicks use the published priority and downward-Y coordinates for all orientations',()=>{
  const expected=[[[0,0],[0,-1],[1,-1],[-1,-1],[1,0],[-1,0]],[[0,0],[1,0],[1,-2],[1,-1],[0,-2],[0,-1]],[[0,0],[0,1],[-1,1],[1,1],[-1,0],[1,0]],[[0,0],[-1,0],[-1,-2],[-1,-1],[0,-2],[0,-1]]];
  for(let r=0;r<4;r++)for(let target=0;target<6;target++){const g=new Game();g.current=clone('L');g.current.y=8;for(let i=0;i<r;i++)g.rotate(1,0);const before={...g.current},tried=[],blocked=g.blocked.bind(g);g.blocked=(p,dx,dy,m)=>{if(m&&m!==p.m){tried.push([dx,dy]);return tried.length<=target;}return blocked(p,dx,dy,m);};assert.equal(g.rotate(2,10),true);assert.deepEqual(tried,expected[r].slice(0,target+1));assert.equal(g.current.x,before.x+expected[r][target][0]);assert.equal(g.current.y,before.y+expected[r][target][1]);}
});
test('invalid rotation and O rotation cannot consume lock delay',()=>{const g=new Game();for(const dir of [0,3,null,NaN])assert.equal(g.rotate(dir,0),false);g.current=clone('O');assert.equal(g.rotate(2,10),false);assert.equal(g.lockResets,0);});
test('hold can be used only once before locking',()=>{const g=new Game();const type=g.current.type;assert.equal(g.holdPiece(10),true);assert.equal(g.hold,type);assert.equal(g.holdPiece(20),false);g.hardDrop(30);assert.equal(g.canHold,true);assert.equal(g.holdPiece(40),true);});
test('swapped hold resets lock and gravity timestamps',()=>{const g=new Game();g.hold='I';g.groundedAt=100;g.gravityAt=50;g.lockResets=15;g.lastRotate=true;g.lastKick=4;assert.equal(g.holdPiece(900),true);assert.equal(g.groundedAt,null);assert.equal(g.lockResets,0);assert.equal(g.gravityAt,900);assert.equal(g.lastRotate,false);assert.equal(g.lastKick,0);assert.equal(g.current.r,0);});
test('hold detects blocked spawn',()=>{const g=new Game();g.hold='O';g.board[0][4]='#abc';g.holdPiece(10);assert.equal(g.over,true);});
test('fixed gravity is identical at 0 and 100 cleared lines',()=>{for(const lines of [0,30,100]){const g=new Game();g.lines=lines;g.update(999);assert.equal(g.current.y,0);g.update(1000);assert.equal(g.current.y,1);g.update(1999);assert.equal(g.current.y,1);g.update(2000);assert.equal(g.current.y,2);}});
test('lock waits 500ms and resets at most 15 times',()=>{const g=new Game();g.current=clone('O');g.current.y=20;g.update(100);assert.equal(g.pieces,0);g.update(599);assert.equal(g.pieces,0);for(let i=0;i<15;i++)assert.equal(g.move(i%2?-1:1,600+i*10),true);assert.equal(g.lockResets,15);const at=g.groundedAt;g.move(-1,at+200);assert.equal(g.groundedAt,at);g.update(at+499);assert.equal(g.pieces,0);g.update(at+500);assert.equal(g.pieces,1);});
test('soft and hard drop points count only traveled cells',()=>{const g=new Game();g.current=clone('O');g.down(10,true);assert.equal(g.score,1);const event=g.hardDrop(20);assert.equal(event.distance,19);assert.equal(g.score,39);assert.equal(g.pieces,1);assert.equal(g.gravityAt,20);});
test('four-row clear compacts board and awards perfect clear',()=>{const g=new Game();well(g);const event=g.hardDrop(100);assert.equal(event.rows.length,4);assert.equal(event.perfect,true);assert.equal(g.lines,4);assert.equal(g.perfects,1);assert.equal(g.tetrises,1);assert.equal(g.score,2800+event.distance*2);assert.equal(g.board.length,22);assert.ok(g.board.every(row=>row.every(v=>!v)));});
test('T-spin without lines earns points and breaks combo, preserves B2B',()=>{assert.deepEqual(scoreClear(0,'T-SPIN',false,3,true),{points:400,combo:-1,b2b:true,chained:false});assert.equal(scoreClear(0,'T-SPIN MINI',false,2,false).points,100);});
test('normal line clears have expected fixed scores',()=>{[0,100,300,500,800].forEach((score,n)=>assert.equal(scoreClear(n,'',false,-1,false).points,score));});
test('B2B continues across non-clears, breaks on an ordinary clear',()=>{let s=scoreClear(4,'',false,-1,false);assert.equal(s.b2b,true);s=scoreClear(0,'',false,s.combo,s.b2b);assert.equal(s.b2b,true);s=scoreClear(4,'',false,s.combo,s.b2b);assert.equal(s.points,1200);assert.equal(s.chained,true);s=scoreClear(1,'',false,s.combo,s.b2b);assert.equal(s.b2b,false);assert.equal(s.points,150);});
test('consecutive clears raise combo and empty locks reset it',()=>{assert.equal(scoreClear(2,'',false,2,false).points,450);assert.equal(scoreClear(0,'',false,3,true).combo,-1);});
test('perfect clear bonuses depend on line count and B2B',()=>{[900,1500,2300,2800].forEach((points,i)=>assert.equal(scoreClear(i+1,'',true,-1,false).points,points));assert.equal(scoreClear(4,'',true,-1,true).points,4400);});
test('three corners and orientation distinguish full and mini T-spin',()=>{const g=new Game();g.current=clone('T');g.current.y=18;g.lastRotate=true;g.lastTurn=1;g.board[18][3]='#abc';g.board[18][5]='#abc';g.board[20][3]='#abc';assert.equal(g.spin(),'T-SPIN');g.board[18][5]=null;g.board[20][5]='#abc';assert.equal(g.spin(),'T-SPIN MINI');g.lastKick=4;assert.equal(g.spin(),'T-SPIN');g.lastTurn=2;assert.equal(g.spin(),'T-SPIN MINI');g.lastRotate=false;assert.equal(g.spin(),'');});
test('T-spin front-corner tests cover all four orientations',()=>{const front=[[0,1],[1,3],[2,3],[0,2]],corners=[[3,10],[5,10],[3,12],[5,12]];for(let r=0;r<4;r++){const g=new Game();g.current=clone('T');g.current.y=10;for(let i=0;i<r;i++)g.rotate(1,0);g.lastRotate=true;g.lastTurn=2;for(let missing=0;missing<4;missing++){g.board=empty();corners.forEach(([x,y],i)=>{if(i!==missing)g.board[y][x]='#abc';});assert.equal(g.spin(),front[r].includes(missing)?'T-SPIN MINI':'T-SPIN');}}});
test('S/Z quarter-turn floor tucks remain mirrored and collision-free',()=>{for(const [type,dir] of [['S',1],['Z',-1]]){const g=new Game();g.current=clone(type);g.current.y=20;assert.equal(g.rotate(dir,10),true);assert.equal(g.lastKick,2);assert.equal(g.current.x,type==='S'?2:4);assert.equal(g.current.y,19);assert.equal(g.blocked(),false);}});
test('zero-distance hard drop preserves valid T-spin and scores it',()=>{const g=new Game();g.current=clone('T');g.current.y=20;g.lastRotate=true;g.board[20][3]='#abc';g.board[20][5]='#abc';const event=g.hardDrop(500);assert.equal(event.distance,0);assert.equal(event.spin,'T-SPIN');assert.equal(g.score,400);assert.equal(g.tspins,1);});
test('translated hard drop does not inherit rotation qualification',()=>{const g=new Game();g.current=clone('T');g.lastRotate=true;g.board[20][3]='#abc';g.board[20][5]='#abc';assert.equal(g.hardDrop(100).spin,'');});
test('full lock-out ends the game even if next spawn is clear',()=>{const g=new Game();g.current=clone('O');g.current.x=0;g.board[2][0]='#abc';g.board[2][1]='#abc';g.lock(50);assert.equal(g.over,true);});
test('random legal input sequences preserve board and piece invariants',()=>{const random=rng(47);let g=new Game(random);for(let i=0;i<12000;i++){if(g.over)g=new Game(random);const now=i*30;switch(Math.floor(random()*7)){case 0:g.move(-1,now);break;case 1:g.move(1,now);break;case 2:g.rotate(1,now);break;case 3:g.rotate(-1,now);break;case 4:g.holdPiece(now);break;case 5:g.hardDrop(now);break;case 6:g.down(now,true);}g.update(now);assert.equal(g.board.length,22);assert.ok(g.board.every(row=>row.length===10));assert.ok(Number.isFinite(g.score)&&g.score>=0);if(!g.over)assert.equal(g.blocked(),false);}});
