'use strict';
(() => {const $=s=>document.querySelector(s),A=TTRSAccount;let rankingMode='battle';
  const textRow=values=>{const tr=document.createElement('tr');for(const value of values){const td=document.createElement('td');td.textContent=String(value);tr.append(td);}return tr;};
  const time=ms=>`${Math.floor(ms/60000)}:${((ms%60000)/1000).toFixed(2).padStart(5,'0')}`;
  async function rankings(){const data=await A.api('/rankings?mode='+rankingMode);$('#ranking-rule').textContent=rankingMode==='battle'?'서버 판정 · 누적 생존 포인트(참가 인원 − 최종 순위), 동점은 우승 횟수 순':'입력 재생 검증 · '+(rankingMode==='sprint'?'40줄 완주 최단 시간':'2분 완주 최고 점수')+' · 계정별 최고 기록';$('#ranking-empty').hidden=data.length>0;$('#ranking-body').replaceChildren(...data.map((r,i)=>textRow([i+1,`${r.nickname}${r.guest?' · 게스트':''}`,rankingMode==='sprint'?time(r.value):`${r.value.toLocaleString()}${rankingMode==='battle'?` pt · ${r.wins}승`:'점'}`,r.games])));}
  async function refresh(){await A.refresh();const u=A.user;$('#identity-label').textContent=`${u.nickname} · ${u.username||'임시 닉네임의 게스트'}`;$('#auth-forms').hidden=Boolean(u.username);$('#logout-button').hidden=!u.username;const records=await A.api('/records');$('#records-empty').hidden=records.length>0;$('#records-body').replaceChildren(...records.map(r=>textRow([new Date(r.created*1000).toLocaleString(),{battle:'ARENA 50',sprint:'40 LINES',attack:'TIME ATTACK'}[r.mode],r.mode==='battle'?`${r.placement} / ${r.participants}위`:r.completed?'완주':'종료',time(r.elapsed),`${r.score}점 / ${r.lines}줄`])));await rankings();}
  async function change(path,data,button){button.disabled=true;try{await A.api(path,data);try{localStorage.setItem('ttrs-auth-change',String(Date.now()));}catch{}await refresh();$('#account-status').textContent='완료했습니다. 진행 중이던 게임 탭은 새로고침해 주세요.';}catch(e){$('#account-status').textContent=e.message;}finally{button.disabled=false;}}
  $('#login-form').onsubmit=e=>{e.preventDefault();change('/login',{username:$('#login-username').value,password:$('#login-password').value},e.submitter).finally(()=>$('#login-password').value='');};
  $('#register-form').onsubmit=e=>{e.preventDefault();change('/register',{username:$('#register-username').value,nickname:$('#register-nickname').value,password:$('#register-password').value},e.submitter).finally(()=>$('#register-password').value='');};
  $('#logout-button').onclick=e=>change('/logout',{},e.currentTarget);
  document.querySelectorAll('[data-ranking]').forEach(b=>b.onclick=()=>{rankingMode=b.dataset.ranking;document.querySelectorAll('[data-ranking]').forEach(e=>e.setAttribute('aria-pressed',String(e===b)));rankings().catch(e=>$('#account-status').textContent=e.message);});
  $('#http-warning').hidden=location.protocol==='https:';A.ready.then(refresh).then(()=>{if(location.pathname==='/rankings')$('#leaderboard').scrollIntoView();}).catch(e=>$('#account-status').textContent=e.message);
})();
