const W=10,H=22,VISIBLE=20,CELL=30,BEST="ttrs-40-lines-best",SETTINGS="ttrs-input-settings";
const PIECES={I:{c:"#35c9d6",m:[[0,0,0,0],[1,1,1,1],[0,0,0,0],[0,0,0,0]]},O:{c:"#f2d247",m:[[1,1],[1,1]]},T:{c:"#a66be0",m:[[0,1,0],[1,1,1],[0,0,0]]},S:{c:"#52bd72",m:[[0,1,1],[1,1,0],[0,0,0]]},Z:{c:"#e75656",m:[[1,1,0],[0,1,1],[0,0,0]]},J:{c:"#518ce2",m:[[1,0,0],[1,1,1],[0,0,0]]},L:{c:"#e99549",m:[[0,0,1],[1,1,1],[0,0,0]]}};
const JL={"0>1":[[0,0],[-1,0],[-1,-1],[0,2],[-1,2]],"1>0":[[0,0],[1,0],[1,1],[0,-2],[1,-2]],"1>2":[[0,0],[1,0],[1,1],[0,-2],[1,-2]],"2>1":[[0,0],[-1,0],[-1,-1],[0,2],[-1,2]],"2>3":[[0,0],[1,0],[1,-1],[0,2],[1,2]],"3>2":[[0,0],[-1,0],[-1,1],[0,-2],[-1,-2]],"3>0":[[0,0],[-1,0],[-1,1],[0,-2],[-1,-2]],"0>3":[[0,0],[1,0],[1,-1],[0,2],[1,2]]};
const IK={"0>1":[[0,0],[-2,0],[1,0],[-2,1],[1,-2]],"1>0":[[0,0],[2,0],[-1,0],[2,-1],[-1,2]],"1>2":[[0,0],[-1,0],[2,0],[-1,-2],[2,1]],"2>1":[[0,0],[1,0],[-2,0],[1,2],[-2,-1]],"2>3":[[0,0],[2,0],[-1,0],[2,-1],[-1,2]],"3>2":[[0,0],[-2,0],[1,0],[-2,1],[1,-2]],"3>0":[[0,0],[1,0],[-2,0],[1,2],[-2,-1]],"0>3":[[0,0],[-1,0],[2,0],[-1,-2],[2,1]]};
const boardCanvas=document.querySelector("#board"),ctx=boardCanvas.getContext("2d"),holdCtx=document.querySelector("#hold").getContext("2d"),nextList=document.querySelector("#next-list"),linesEl=document.querySelector("#lines"),timeEl=document.querySelector("#time"),bestEl=document.querySelector("#best"),scoreEl=document.querySelector("#score"),levelEl=document.querySelector("#level"),eventEl=document.querySelector("#event-text"),comboEl=document.querySelector("#combo-text"),b2bEl=document.querySelector("#b2b-text"),overlay=document.querySelector("#overlay"),status=document.querySelector("#status");
let board,queue,current,hold=null,canHold=true,running=false,lines=0,score=0,level=1,combo=-1,b2b=false,lastRotate=false,lastKick=0,startedAt=0,elapsed=0,lastFrame=0,gravityAt=0,groundedAt=null,lockResets=0,frame,keys={},repeatAt=0,softAt=0;
let prefs={das:133,arr:10,ghost:true};try{prefs={...prefs,...JSON.parse(localStorage.getItem(SETTINGS))};}catch(_){}
function clone(type){return {type,c:PIECES[type].c,m:PIECES[type].m.map(r=>[...r]),x:3,y:0,r:0};}
function bag(){return Object.keys(PIECES).sort(()=>Math.random()-.5);}
function refill(){while(queue.length<6)queue.push(...bag());}
function newBoard(){return Array.from({length:H},()=>Array(W).fill(null));}
function fmt(ms){const n=Math.floor(ms/10),m=Math.floor(n/6000),s=Math.floor(n/100)%60,c=n%100;return `${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}.${String(c).padStart(2,"0")}`;}
function cell(context,x,y,color,size=CELL){if(y<0)return;context.fillStyle=color||"#151a1e";context.fillRect(x*size+1,y*size+1,size-2,size-2);}
function pieceCells(piece,fn){piece.m.forEach((row,y)=>row.forEach((v,x)=>{if(v)fn(piece.x+x,piece.y+y,x,y);}));}
function blocked(piece,dx=0,dy=0,matrix=piece.m){return matrix.some((row,y)=>row.some((v,x)=>v&&(piece.x+x+dx<0||piece.x+x+dx>=W||piece.y+y+dy>=H||(piece.y+y+dy>=0&&board[piece.y+y+dy][piece.x+x+dx]))));}
function isGrounded(){return blocked(current,0,1);}
function resetLock(){if(isGrounded()&&lockResets<15){groundedAt=performance.now();lockResets++;}else if(!isGrounded())groundedAt=null;}
function rotated(m,dir){if(dir===-1)return m[0].map((_,i)=>m.map(r=>r[r.length-1-i]));return m[0].map((_,i)=>m.map(r=>r[i]).reverse());}
function rotate(dir){if(dir===2){rotate(1);rotate(1);return;}if(!running||current.type==="O")return;const old=current.r,target=(old+(dir===-1?3:1))%4,m=rotated(current.m,dir);const tests=(current.type==="I"?IK:JL)[`${old}>${target}`]||[[0,0]];for(let i=0;i<tests.length;i++){const [x,y]=tests[i];if(!blocked(current,x,y,m)){current.x+=x;current.y+=y;current.m=m;current.r=target;lastRotate=true;lastKick=i;resetLock();return;}}}
function move(dx){if(!running||blocked(current,dx))return false;current.x+=dx;lastRotate=false;resetLock();return true;}
function softDrop(){if(!running)return;if(!blocked(current,0,1)){current.y++;score++;lastRotate=false;groundedAt=null;}else if(!groundedAt)groundedAt=performance.now();}
function hardDrop(){if(!running)return;let d=0;while(!blocked(current,0,1)){current.y++;d++;}score+=d*2;lock();}
function typeOfSpin(){if(current.type!=="T"||!lastRotate)return "";const px=current.x+1,py=current.y+1;const occupied=([x,y])=>x<0||x>=W||y>=H||(y>=0&&board[y][x]);const corners=[[px-1,py-1],[px+1,py-1],[px-1,py+1],[px+1,py+1]],solid=corners.filter(([x,y])=>occupied([x,y])).length;if(solid<3)return "";const front=[[[px-1,py-1],[px+1,py-1]],[[px+1,py-1],[px+1,py+1]],[[px-1,py+1],[px+1,py+1]],[[px-1,py-1],[px-1,py+1]]][current.r];return front.every(([x,y])=>occupied([x,y]))||lastKick===4?"T-SPIN":"T-SPIN MINI";}
function clearRows(){let n=0;board=board.filter(row=>{if(row.every(Boolean)){n++;return false;}return true;});while(board.length<H)board.unshift(Array(W).fill(null));return n;}
function applyScore(cleared,spin,perfect){const names=["","SINGLE","DOUBLE","TRIPLE","TETRIS"],normal=[0,100,300,500,800],tspin=[400,800,1200,1600],mini=[100,200,400];let base=spin==="T-SPIN MINI"?mini[cleared]||100:spin?tspin[cleared]||400:normal[cleared];const difficult=(cleared===4)||(spin&&cleared>0),wasB2B=b2b;if(difficult&&wasB2B)base=Math.floor(base*1.5);if(perfect)base+=3500;if(cleared){combo++;score+=base*level+(combo>0?50*combo*level:0);b2b=difficult;}else if(!spin)combo=-1;if(!cleared&&!spin)return;eventEl.textContent=`${spin?`${spin} ${names[cleared]||""}`:names[cleared]||"T-SPIN"}${perfect?" · PERFECT CLEAR":""}${wasB2B&&difficult?" · B2B":""}`.trim();comboEl.textContent=combo>0?`COMBO × ${combo}`:"COMBO —";b2bEl.textContent=b2b?"B2B ACTIVE":"B2B —";}
function lock(){const spin=typeOfSpin();pieceCells(current,(x,y)=>{if(y>=0)board[y][x]=current.c;});const cleared=clearRows(),perfect=cleared>0&&board.every(row=>row.every(v=>!v));applyScore(cleared,spin,perfect);lines+=cleared;level=Math.floor(lines/10)+1;linesEl.innerHTML=`${Math.min(lines,40)} <small>/ 40</small>`;scoreEl.textContent=score.toLocaleString();levelEl.textContent=level;if(lines>=40){finish(true);return;}spawn();}
function spawn(){refill();current=clone(queue.shift());refill();current.x=Math.floor((W-current.m[0].length)/2);current.y=0;canHold=true;lastRotate=false;lastKick=0;groundedAt=null;lockResets=0;if(blocked(current))finish(false);drawPreviews();}
function holdPiece(){if(!running||!canHold)return;const old=hold;hold=current.type;if(old){current=clone(old);current.x=Math.floor((W-current.m[0].length)/2);current.y=0;if(blocked(current))finish(false);}else spawn();canHold=false;lastRotate=false;drawPreviews();}
function drawMini(context,type,w,h){context.fillStyle="#0e1113";context.fillRect(0,0,w,h);if(!type)return;const p=clone(type),s=Math.min(20,Math.floor(Math.min(w/(p.m[0].length+2),h/(p.m.length+2))),),ox=(w-p.m[0].length*s)/2,oy=(h-p.m.length*s)/2;context.fillStyle=p.c;p.m.forEach((row,y)=>row.forEach((v,x)=>{if(v){context.fillRect(ox+x*s+1,oy+y*s+1,s-2,s-2);}}));}
function drawPreviews(){drawMini(holdCtx,hold,120,120);nextList.innerHTML="";queue.slice(0,5).forEach(type=>{const c=document.createElement("canvas");c.width=158;c.height=62;c.className="next-item";nextList.append(c);drawMini(c.getContext("2d"),type,158,62);});}
function draw(){ctx.fillStyle="#101316";ctx.fillRect(0,0,300,600);board.forEach((row,y)=>row.forEach((v,x)=>{if(y>=2)cell(ctx,x,y-2,v);}));if(current&&prefs.ghost){let gy=current.y;while(!blocked({...current,y:gy},0,1))gy++;pieceCells({...current,y:gy},(x,y)=>{if(y>=2){ctx.fillStyle="rgba(210,220,225,.18)";ctx.fillRect(x*CELL+5,(y-2)*CELL+5,CELL-10,CELL-10);}});}if(current)pieceCells(current,(x,y)=>{if(y>=2)cell(ctx,x,y-2,current.c);});}
function gravity(){return Math.max(50,Math.round(1000*Math.pow(.8-.007*(level-1),level-1)));}
function finish(won){running=false;cancelAnimationFrame(frame);elapsed=performance.now()-startedAt;timeEl.textContent=fmt(elapsed);overlay.hidden=false;overlay.querySelector("strong").textContent=won?"COMPLETE":"GAME OVER";overlay.querySelector("span").textContent=won?`${fmt(elapsed)} · ${score.toLocaleString()} PTS`:"RESTART 또는 R 키";if(won){const old=Number(localStorage.getItem(BEST));if(!old||elapsed<old){localStorage.setItem(BEST,String(elapsed));bestEl.textContent=fmt(elapsed);status.textContent="NEW BEST · 이 브라우저에 기록을 저장했습니다.";}else status.textContent="COMPLETE · 최고 기록에 다시 도전하세요.";}}
function processHeld(now){const dir=keys.ArrowLeft?-1:keys.ArrowRight?1:0;if(dir&&now>=repeatAt){if(prefs.arr===0){while(move(dir));repeatAt=now+16;}else{move(dir);repeatAt=now+prefs.arr;}}if(keys.ArrowDown&&now-softAt>=35){softDrop();softAt=now;}}
function tick(now){if(!running)return;elapsed=now-startedAt;timeEl.textContent=fmt(elapsed);scoreEl.textContent=score.toLocaleString();processHeld(now);if(now-gravityAt>=gravity()&&!isGrounded()){current.y++;lastRotate=false;gravityAt=now;groundedAt=null;}if(isGrounded()){if(!groundedAt)groundedAt=now;if(now-groundedAt>=500)lock();}draw();frame=requestAnimationFrame(tick);}
function start(){board=newBoard();queue=[];refill();hold=null;lines=0;score=0;level=1;combo=-1;b2b=false;elapsed=0;spawn();running=true;startedAt=performance.now();gravityAt=startedAt;groundedAt=null;linesEl.innerHTML="0 <small>/ 40</small>";timeEl.textContent="00:00.00";scoreEl.textContent="0";levelEl.textContent="1";eventEl.textContent="—";comboEl.textContent="COMBO —";b2bEl.textContent="B2B —";overlay.hidden=true;status.textContent="40줄을 지우면 기록이 저장됩니다.";cancelAnimationFrame(frame);draw();frame=requestAnimationFrame(tick);}
function action(a){if(a==="left")move(-1);if(a==="right")move(1);if(a==="down")softDrop();if(a==="drop")hardDrop();if(a==="hold")holdPiece();if(a==="rotate-right")rotate(1);if(a==="rotate-left")rotate(-1);draw();}
document.querySelector("#start-button").onclick=start;document.querySelector("#restart-button").onclick=start;document.querySelectorAll("[data-control]").forEach(b=>b.onclick=()=>action(b.dataset.control));
document.addEventListener("keydown",e=>{const k=e.code==="Space"?"Space":e.key;if(["ArrowLeft","ArrowRight","ArrowDown","ArrowUp","Space"].includes(k))e.preventDefault();if(e.repeat)return;if(k==="r"||k==="R")return start();if(k==="c"||k==="C"||k==="Shift")return holdPiece();if(k==="ArrowUp"||k==="x"||k==="X")return rotate(1);if(k==="z"||k==="Z")return rotate(-1);if(k==="a"||k==="A")return rotate(2);if(k==="Space")return hardDrop();if(["ArrowLeft","ArrowRight","ArrowDown"].includes(k)){keys[k]=true;if(k!=="ArrowDown"){move(k==="ArrowLeft"?-1:1);repeatAt=performance.now()+prefs.das;}else softDrop();}});
document.addEventListener("keyup",e=>{const k=e.key;keys[k]=false;if(k==="ArrowLeft"||k==="ArrowRight")repeatAt=performance.now()+prefs.das;});
const dialog=document.querySelector("#settings-dialog"),das=document.querySelector("#das-input"),arr=document.querySelector("#arr-input"),ghost=document.querySelector("#ghost-input");function syncSettings(){das.value=prefs.das;arr.value=prefs.arr;ghost.checked=prefs.ghost;document.querySelector("#das-value").textContent=`${prefs.das} ms`;document.querySelector("#arr-value").textContent=prefs.arr===0?"INSTANT":`${prefs.arr} ms`;}document.querySelector("#settings-button").onclick=()=>{syncSettings();dialog.showModal();};das.oninput=()=>{prefs.das=Number(das.value);syncSettings();};arr.oninput=()=>{prefs.arr=Number(arr.value);syncSettings();};ghost.onchange=()=>prefs.ghost=ghost.checked;document.querySelector("#save-settings").onclick=()=>localStorage.setItem(SETTINGS,JSON.stringify(prefs));
const saved=Number(localStorage.getItem(BEST));if(saved)bestEl.textContent=fmt(saved);board=newBoard();queue=[];refill();current=clone(queue[0]);drawPreviews();draw();
